create table if not exists games (
    id integer primary key,
    name text not null,
    kills integer not null,
    deaths integer not null,
    assists integer not null,
    primary_rune integer not null,
    secondary_rune integer not null,
    summoner_spell_1 integer not null,
    summoner_spell_2 integer not null,
    champion_id integer not null,
    champion_name text not null,
    game_duration integer not null,
    game_completion_time integer not null,
    win boolean not null,
    match_id text not null,
    item_0 integer not null,
    item_1 integer not null,
    item_2 integer not null,
    item_3 integer not null,
    item_4 integer not null,
    item_5 integer not null,
    item_6 integer not null,
    md5sum text not null unique
);
