ALTER TABLE games
ADD COLUMN item_0 INT NOT NULL,
ADD COLUMN item_1 INT NOT NULL,
ADD COLUMN item_2 INT NOT NULL,
ADD COLUMN item_3 INT NOT NULL,
ADD COLUMN item_4 INT NOT NULL,
ADD COLUMN item_5 INT NOT NULL,
ADD COLUMN item_6 INT NOT NULL;